### ISSUE TITLE
PHP ought to set bits 4 and 5

### ISSUE THREAD

**Issue by matozoid** [cadaver/siddump#1]
Hi! I'm making a conversion of the 6502 emulator to Java and found a small bug. See https://wiki.nesdev.com/w/index.php/Status_flags

(Also: please say so if there is an issue with converting it to Java, since there is a copyright on this. It's not going to be used commercially anyway.)

**Comment by matozoid** [comment]
(Here it is: https://github.com/laamella-gad/Mpu6502 )

**Comment by cadaver** [comment]
Thanks. And sorry for not looking into the issues in a long time, I hadn't been following the repo. To comply with the BSD license you should copy the license text into either your source files or into a COPYING or README file in the project.

**Comment by matozoid** [comment]
Alright, I chucked a BSD-3 license into it.
