### ISSUE TITLE
Build fails on Ubuntu 20.04LTS / ARM64 (siddump.c:(.text.startup+0x19c): undefined reference to `pow')

### ISSUE THREAD

**Issue by pseudofunizer** [cadaver/siddump#4]
Hi there!

Been trying to compile SIDdump for my Raspberry Pi4B box (=ARM64/aarch64) that is running on 64bit Ubuntu 20.04.1LTS. It's been my attempt to create a nice little cross-development platform for an old friend of mine who's hopelessly stuck in the C64 era. :-) 

Previously I've managed to get i.e. `siddasm` to compile and work just fine, but for some reason compiling `siddump` brings this kind of error:

```
$ make
gcc -O3 -Wall   -c -o siddump.o siddump.c
siddump.c: In function ‘main’:
siddump.c:245:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  245 |   fread(&mem[loadaddress], loadsize, 1, in);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
siddump.c: In function ‘readbyte’:
siddump.c:504:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  504 |   fread(&res, 1, 1, f);
      |   ^~~~~~~~~~~~~~~~~~~~
siddump.c: In function ‘readword’:
siddump.c:512:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  512 |   fread(&res, 2, 1, f);
      |   ^~~~~~~~~~~~~~~~~~~~
gcc -O3 -Wall   -c -o cpu.o cpu.c
gcc -o siddump.exe siddump.o cpu.o
/usr/bin/ld: siddump.o: in function `main':
siddump.c:(.text.startup+0x19c): undefined reference to `pow'
collect2: error: ld returned 1 exit status
make: *** [Makefile:7: siddump.exe] Error 1
```

Any ideas on where I should start with the bug hunt?

**Comment by pseudofunizer** [comment]
Whoops, just noticed that in `sidid`, it was mentioned in the readme.txt that it's only for win32? I guess the case is the same with this tool? If so, well, that's too bad. :( Thanks anyway.

**Comment by cadaver** [comment]
These utilities shouldn't be win32-only per se, but the makefiles are almost never tested on anything else than Windows. In this case it looks like a new requirement that the math library needs to be explicitly linked with -lm switch. I'll see the makefile can be edited to work with both OSes.
